dataset_type: "blender" # [tiny_nerf, custom, blender]
dataset_path: "data/lego"
ckpt_path: "checkpoints/lego_blender_ngp_checkpoint.pt"

# ngp parameters
rays_per_batch: 2048
near: 2.0
far: 6.0
samples_per_ray: 591 # 1024/sqrt(3)
perturb_samples: True
scene_scale: 0.3333 # Downsizing factor to bring scene within [0, 1]^3
T: 524288 # 2**19 # Hash table size
Nmin: 16 # Minimum grid resolution
Nmax: 2048 # Maximum grid resolution
Nlevels: 16 # Number of levels
L: 4 # Number of frequencies for encoding
d: 3 # grid dimension
F: 2 # Number of feature channels
occupancy_grid_res: 128 # For accelerated raymarching
t_thresh: 0.0001 # 1e-4 # Transmittance threshold

# training parameters
lr: 0.01
epochs: 10000
val_interval: 250
save_interval: 250