dataset_type: "ImageRecon" # [tiny_nerf, custom, blender, ImageRecon]
dataset_path: "/root/NeRF_from_scratch/data/megapixel_tokyo.jpg" # 6144 x 2324 x 3 = 42,835,968
ckpt_path: "checkpoints/img_recon_ngp_checkpoint.pt"

# ngp parameters
rays_per_batch: 640000
near: 1.0
far: 1.0
samples_per_ray: 1
perturb_samples: False
scene_scale: 0.5                      # Downsizing factor to bring scene within [0, 1]^3
T: 524288                             # 2**19 # Hash table size
Nmin: 16                              # Minimum grid resolution
Nmax: 2048                            # Maximum grid resolution
Nlevels: 16                           # Number of levels
L: 2                                  # Number of frequencies for encoding directions
d: 2                                  # grid dimension
F: 2                                  # Number of feature channels
occupancy_grid_res: 128               # For accelerated raymarching
occ_decay: 0.90                       # occupancy decay rate (0.95 in paper)
t_thresh: 0.0001                      # 1e-4 # Transmittance threshold

# training parameters
lr: 0.01
epochs: 350
val_interval: 25
save_interval: 25