dataset_type: "tiny_nerf" # [tiny_nerf, custom, blender]
dataset_path: "data/lego_200x200.npz"
ckpt_path: "checkpoints/fine_lego_nerf_checkpoint.pt"

# nerf parameters
rays_per_batch: 2000
near: 2.0
far: 6.0
samples_per_ray: 64
fine_samples_per_ray: 128
perturb_samples: True

# training parameters
lr: 0.0005
lr_decay_interval: 2000
epochs: 6000
val_interval: 50
save_interval: 50